### ISSUE TITLE
How to work with subword model?

### ISSUE THREAD

**Issue by nvidiaman** [asyml/texar#116]
Hi,

In the transformer example there is a way to learn spm vocabulary.

My question is:

1. Is it a one time thing? i.e. can I just create my vocabulary using this and work with other models like seq2seq.

or

2. I have top do something at decoding too? What do I need to do to compute BLEU scores with these spm vocabularies?

Please let me know any helpful links or answers.

Thank you.

**Comment by ZhitingHu** [comment]
Learning spm vocab is a one-time effort -- it depends only on the dataset instead of the model you wanna learn.

A model learned with spm-encoded data will generate spm-encoded text. To evaluate BLEU, you would first use `bin/utils/spm_decode` to decode the generated text into plain text. See [this section](https://github.com/asyml/texar/tree/master/examples/transformer#test-a-trained-model) of README

**Comment by nvidiaman** [comment]
@ZhitingHu thank you for the answer!
