### ISSUE TITLE
hierarchical_dialog generate text questions

### ISSUE THREAD

**Issue by qichaotang** [asyml/texar#193]
hierarchical_dialog should provide test scripts, decoder to text 
for example, 
inputs: AAA
outputs: BBB

**Comment by qichaotang** [comment]
https://github.com/asyml/texar/blob/master/examples/gpt-2/gpt2_generate_main.py gpt-2 provide

**Comment by ZhitingHu** [comment]
Generated samples can be accessed [here](https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L269) (w/ random sample decoding) and [here](https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L271) (w/ beam search decoding)

**Comment by qichaotang** [comment]
I see it, beam_sample_text, beam_lengths should be generate 's text, this example data is not general, because other data don't have data_batch['refs_text']. why not to compare target's reply with source's generate nlg

**Comment by ZhitingHu** [comment]
I feel this can be achieved with simple tweaks of the current code. The examples are mainly for demonstrating the use of core modules, while adapting to particular datasets/settings should be straightforwardly done. 

We welcome any contributions of course :)

**Comment by qichaotang** [comment]
@ZhitingHu thks your reply. I have new question about data preprocessing, 
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py#L85
inputs:
dialogue_session:
A B
outputs:
no result...

**Comment by TomNong** [comment]
Hi @qichaotang , could you provide more detail of the operation you made in your new question? 

As I understand, you want to check the variables in https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py#L85. In this case you cannot see them because `sw1c2r` is not called if `data_root` exists: https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py#L194-L209, you may remove the downloaded data before checking the variables.

**Comment by qichaotang** [comment]
@TomNong thanks for your reply, 
I have two question.

First question:
in my Scenes, dialogue session data is:
user_query_1 bot_reply_1
user_query_2 bot_reply_2
...
In my opinion, I only need to predict bot_reply by using user's query-reply context.
So I need construct model's input
user_query_1 -> bot_reply_1
user_query_1|||bot_reply_1|||user_query_2 -> bot_reply_2

So I modify this preprocess's scripts
![image](https://user-images.githubusercontent.com/12878507/63079360-b70f8200-bf70-11e9-89d6-3c7ae15424c0.png)

Are you think this modify ok ?

**Comment by qichaotang** [comment]
Second question:
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py#L220
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py#L225

{}-source-spk-{}.txt and {}-target-spk.txt 's effect is distinguish the dialogists. In your example, The dialogists A and B is equal. this will be two states:
One: A's Context -> B_reply
Two: B's Context -> A_reply
So you need the {}-source-spk-{}.txt and {}-target-spk.txt.

In my opinion, In your example, The dialogists A and B is not equal. this will be one states:
One: A's Context -> B_reply

So I can del the {}-source-spk-{}.txt and {}-target-spk.txt ?  And I need modify this model file to del this two file's tensor calc

**Comment by TomNong** [comment]
@qichaotang thanks for the information. For the first question, I'm not sure because we can't verify your dataset. I would suggest you to test your assumption on current example data, then it would probably work for your own data.

For the second question, I don't think `{}-source-spk-{}.txt` and `{}-target-spk.txt` should be deleted, because we can't verify your assumption now. But you can make your test by modifying the example to prove it, and feel free to let us know.

**Comment by qichaotang** [comment]
@TomNong Two question may be related with my Scenes.
But third question:
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L58
![image](https://user-images.githubusercontent.com/12878507/63168400-9d506680-c066-11e9-9fa6-951cb9ceb22b.png)
for one batch, data_batch['source_length']'s utterance_cnt < config_data.max_utterance_cnt, 
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L62
![image](https://user-images.githubusercontent.com/12878507/63168717-78102800-c067-11e9-856e-e2754b74105b.png)
this will be shape's diff, this is bug！！！

**Comment by TomNong** [comment]
@qichaotang for the new question I checked with the test results, https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L62 will not cause error because `data_batch['source_length']`'s size is compatible with `spk_src`. If you encounter error at that point, could you screen the error message and the operation details?

**Comment by qichaotang** [comment]
@TomNong because your test data 's reason. while I use other test data, this will be an question

**Comment by qichaotang** [comment]
https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/config_data.py#L14
https://github.com/asyml/texar/blob/master/texar/tf/data/data_decoders.py#L346
max_utterance_cnt = 9
data demo
for a batch
AA||BB||CC -> DD
AA -> BB
for this batch data, utterance_cnt_shape = 3
data_batch['source_length']'s utterance_cnt  == 3
config_data.max_utterance_cnt == 9
this tf.concat will be error, because shape's diff

**Comment by TomNong** [comment]
@qichaotang  thanks for the information, the `max_utterance_cnt = 9` you mentioned is compatible with the dataset we use, you can refer to https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/sw_loader.py to see how we generate the utterance.

As I understand, you are using a dataset with different utterance size. For our example, you are welcomed to customize the `config_data.py` to fit your data, since our examples is aimed to demo the usage for Texar with certain data.

**Comment by ZhitingHu** [comment]
closed due to inactivity
