### ISSUE TITLE
How to run bert on GPU 

### ISSUE THREAD

**Issue by santhoshkolloju** [asyml/texar#75]
How to run the bert model on gpu?

**Comment by haoransh** [comment]
Texar is built on top of Tensorflow. You need to install `tensorflow-gpu` with pip to run bert on GPU. Reference: https://www.tensorflow.org/install/pip

**Comment by santhoshkolloju** [comment]
Does it mean after installing the Tensorflow gpu.. I have to manually do device placement for each of the encoder module?

**Comment by haoransh** [comment]
You don't need to manually specify the device placement.
If you use single GPU, you don't need to manually specify device placement since all variables will be placed on the default device(GPU).
If you want to use multiple GPUs, data parallel is supported and all of the variables will be placed on all GPUs. https://github.com/asyml/texar/tree/master/examples/bert#train-and-evaluate
